#!/bin/bash

set -e

version='1.4.1'

# AzireVPN uses purples; so shall we :)
darkPurpleBackground='\e[48;5;54m'
lightPurpleForeground='\e[38;5;177m'
padding='  '
lineStart="${padding}${darkPurpleBackground}${lightPurpleForeground}"
lineEnd='\e[0m'

echo
echo -e "${lineStart}                                             ${lineEnd}"
echo -e "${lineStart}  vpn v${version} ­– AzireVPN Wireguard interface  ${lineEnd}"
echo -e "${lineStart}                                             ${lineEnd}"
echo

echo -e " 📦 Installing locally…"

sudo mkdir -p /usr/local/bin/
sudo cp ./vpn /usr/local/bin/

echo -e " 🎉 Done!"
echo
echo -e "To start type ${lightPurple}vpn${colorEnd}."
echo -e "For help type ${lightPurple}vpn help${colorEnd}."
echo
