#!/bin/bash

set -e

echo '\n 📡 Downloading vpn v1.2.0…\n'

wget -qO /tmp/vpn "https://source.small-tech.org/aral/vpn/-/raw/master/vpn?inline=false"

lightPurple='\e[38;5;134m'
colorEnd='\e[0m'

echo
echo -e " 📦 Installing…"

sudo mkdir -p /usr/local/bin/
sudo cp /tmp/vpn /usr/local/bin/
sudo chmod +x /usr/local/bin/vpn

echo -e " 🎉 Done!"
echo
echo -e "To start type ${lightPurple}vpn${colorEnd}."
echo -e "For help type ${lightPurple}vpn help${colorEnd}."
echo
