#!/bin/bash

set -e

version='1.2.0'

# AzireVPN uses purples; so shall we :)
darkPurple='\e[38;5;61m'
lightPurple='\e[38;5;134m'
colorEnd='\e[0m'

echo
echo -e "  ${darkPurple}╔═══════════════════════════════════════════╗${colorEnd}"
echo -e "  ${darkPurple}║${colorEnd}${lightPurple} vpn v${version} ­– AzireVPN Wireguard interface ${colorEnd}${darkPurple}║${colorEnd}"
echo -e "  ${darkPurple}╚═══════════════════════════════════════════╝${colorEnd}"
echo

echo -e ' 📡 Downloading vpn v1.2.0…'

wget -qO /tmp/vpn "https://source.small-tech.org/aral/vpn/-/raw/master/vpn?inline=false"

echo
echo -e " 📦 Installing…"

sudo mkdir -p /usr/local/bin/
sudo cp /tmp/vpn /usr/local/bin/
sudo chmod +x /usr/local/bin/vpn

echo -e " 🎉 Done!"
echo
echo -e "    To start type ${lightPurple}vpn${colorEnd}."
echo -e "    For help type ${lightPurple}vpn help${colorEnd}."
echo
