#!/bin/bash

set -e

version='1.4.1'

# AzireVPN uses purples; so shall we :)
darkPurpleBackground='\e[48;5;54m'
lightPurpleForeground='\e[38;5;177m'
padding='  '
lineStart="${padding}${darkPurpleBackground}${lightPurpleForeground}"
lineEnd='\e[0m'

echo
echo -e "${lineStart}                                             ${lineEnd}"
echo -e "${lineStart}  vpn v${version} ­– AzireVPN Wireguard interface  ${lineEnd}"
echo -e "${lineStart}                                             ${lineEnd}"
echo

echo -e " 📡 Downloading vpn v${version}…"

wget -qO /tmp/vpn "https://source.small-tech.org/aral/vpn/-/raw/master/vpn?inline=false"

echo
echo -e " 📦 Installing…"

sudo mkdir -p /usr/local/bin/
sudo cp /tmp/vpn /usr/local/bin/
sudo chmod +x /usr/local/bin/vpn

echo -e " 🎉 Done!"
echo
echo -e "    To start type ${lightPurple}vpn${colorEnd}."
echo -e "    For help type ${lightPurple}vpn help${colorEnd}."
echo
